require include/opizero3.inc

KERNEL_DTB_FILE = "sun50i-h618-orangepi-zero3.dtb"
KERNEL_DEVICETREE = "allwinner/${KERNEL_DTB_FILE}"
UBOOT_MACHINE = "orangepi_zero3_defconfig"
SPL_BINARY = "u-boot-sunxi-with-spl.bin"

# as for now neither graphics nor audio is supported
MACHINE_FEATURES:remove = "alsa x11"
MACHINE_FEATURES:append = "bluetooth wifi"
MACHINE_EXTRA_RRECOMMENDS = "uwe5622-firmware kernel-modules"

IMAGE_BOOT_FILES = "\
    ${KERNEL_IMAGETYPE} \
    boot.scr \
    ${KERNEL_DTB_FILE} \
"
