# Based on 'orange-pi-zero2.conf' from meta-sunxi but using different:
# * Kernel device tree (from upstream)
# * U-boot machine (from upstream)
#
# orange-pi-zero3 SoC (H618) is very similar to orange-pi-zero2 (H616)
#

require conf/machine/include/sun50i-h616.inc

# "Act" as an orange-pi-zero2 for all other recipes which don't have explicit
# support for orange-pi-zero3
MACHINEOVERRIDES:prepend = "orange-pi-zero2:"
KERNEL_DTB_FILE = "sun50i-h618-orangepi-zero3.dtb"
KERNEL_DEVICETREE = "allwinner/${KERNEL_DTB_FILE}"
UBOOT_MACHINE = "orangepi_zero3_defconfig"
IMAGE_BOOT_FILES = "${KERNEL_IMAGETYPE} boot.scr ${KERNEL_DTB_FILE}"
SPL_BINARY = "u-boot-sunxi-with-spl.bin"

# as for now neither graphics nor audio is supported
MACHINE_FEATURES:remove = "alsa x11"
MACHINE_FEATURES:append = "bluetooth wifi"
MACHINE_EXTRA_RRECOMMENDS = "uwe5622-firmware kernel-modules"

PREFERRED_PROVIDER_virtual/kernel = "linux-stable"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
