require include/raspi3ap.inc

UBOOT_MACHINE = "qemu_arm64_defconfig"
IMAGE_FSTYPES = "tar.bz2 ext4"


# QEMU
IMAGE_CLASSES += "qemuboot"
QB_SYSTEM_NAME = "qemu-system-aarch64"

# Generic arm64 emulation
QB_MACHINE = "-machine virt"
QB_CPU = "-cpu cortex-a7"
QB_SMP ?= "-smp 4"
QB_MEM = "-m 512"
#QB_CPU_KVM = "-cpu host -machine gic-version=3"

QB_ROOTFS_OPT = "\
    -drive if=none,file=@ROOTFS@,format=raw,id=mmc0 \
    -device virtio-blk-device,drive=mmc0 \
"

# Virtio serial console
QB_SERIAL_OPT = "\
    -device virtio-serial-pci -chardev null,id=virtcon \
    -device virtconsole,chardev=virtcon \
"

QB_TCPSERIAL_OPT = "\
    -device virtio-serial-pci -chardev socket,id=virtcon,port=@PORT@,host=127.0.0.1,nodelay=on \
    -device virtconsole,chardev=virtcon \
"
