# WORK IN PROGRESS
# TODOs: 
# - use raspi3ap qemu machine
#   - use raspi3ap uboot defconfig
#   - use raspi3ap kernel dtb

#require conf/machine/qemuarm.conf
require conf/machine/include/arm/armv7a/tune-cortexa7.inc
require conf/machine/include/qemu.inc
include conf/machine/include/rpi-base.inc

# "Act" as a raspberrypi3 for all other recipes which don't have explicit
# support for qemu-raspi3ap machine
MACHINEOVERRIDES:prepend = "raspberrypi3:"
KERNEL_DTB_FILE = "qemu_raspi3ap.dtb"
KERNEL_IMAGETYPE = "zImage"
# TODO: test with rpi_3_32b_config UBOOT_MACHINE
UBOOT_MACHINE = "qemu_arm_defconfig"
BOOT_SCRIPT_FILE = "boot.scr"

UBOOT_ENTRYPOINT =       "0x00008000"
UBOOT_LOADADDRESS =      "0x00008000"
KERNEL_EXTRA_ARGS += "LOADADDR=${UBOOT_ENTRYPOINT}"

IMAGE_FSTYPES:append = " wic.qcow2"
WKS_FILE = "qemu-test.wks"

unset MACHINE_EXTRA_RRECOMMENDS
MACHINE_EXTRA_RRECOMMENDS = ""

unset IMAGE_BOOT_FILES
IMAGE_BOOT_FILES = "${KERNEL_IMAGETYPE} ${KERNEL_DTB_FILE} ${BOOT_SCRIPT_FILE}"

unset KERNEL_DEVICETREE
KERNEL_DEVICETREE = ""

PREFERRED_PROVIDER_virtual/kernel = "linux-stable"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"


# For runqemu
QB_SYSTEM_NAME = "qemu-system-arm"
QB_MACHINE = "-machine virt"
QB_CPU = "-cpu cortex-a7"
QB_SMP ?= "-smp 4"
QB_CPU_KVM = "-cpu host -machine gic-version=3"

do_image_wic[depends] += " \
    u-boot:do_deploy \
    qemu-devicetree:do_deploy \
"

QB_ROOTFS_OPT = "\
    -drive id=disk0,file=@ROOTFS@,if=none,format=qcow2 \
    -device virtio-blk-device,drive=disk0 \
"

QB_SERIAL_OPT = "\
    -device virtio-serial-pci -chardev null,id=virtcon \
    -device virtconsole,chardev=virtcon \
"

QB_TCPSERIAL_OPT = "\
    -device virtio-serial-pci -chardev socket,id=virtcon,port=@PORT@,host=127.0.0.1,nodelay=on \
    -device virtconsole,chardev=virtcon \
"

QB_OPT_APPEND = "-bios ${DEPLOY_DIR_IMAGE}/u-boot.bin"
