# WORK IN PROGRESS
# Major todo: use linux-stable kernel

require conf/machine/qemuarm.conf

KERNEL_DTB_FILE = "qemu_raspi3ap.dtb"

# Use the same overrides as qemuarm machine
MACHINEOVERRIDES:append = ":qemuarm"

UBOOT_ENTRYPOINT =       "0x00008000"
UBOOT_LOADADDRESS =      "0x00008000"


KERNEL_IMAGETYPE = "zImage"
KERNEL_EXTRA_ARGS += "LOADADDR=${UBOOT_ENTRYPOINT}"


IMAGE_FSTYPES:append = " wic.qcow2"

WKS_FILE = "qemu-test.wks"

IMAGE_BOOT_FILES = "zImage ${KERNEL_DTB_FILE} boot.scr"

do_image_wic[depends] += " \
    u-boot:do_deploy \
    qemu-devicetree:do_deploy \
"

QB_ROOTFS_OPT = "-drive id=disk0,file=@ROOTFS@,if=none,format=qcow2 -device virtio-blk-device,drive=disk0"
