# Based on 'opizero3.conf' and 'qemuarm64.conf'

require conf/machine/include/arm/armv8a/tune-cortexa53.inc
require conf/machine/include/qemu.inc

# "Act" as an orange-pi-zero2 for all other recipes which don't have explicit
# support for orange-pi-zero3 which we're emulating with this machine
MACHINEOVERRIDES:prepend = "orange-pi-zero2:"
KERNEL_DTB_FILE = "sun50i-h618-orangepi-zero3.dtb"
KERNEL_DEVICETREE = "allwinner/${KERNEL_DTB_FILE}"
KERNEL_IMAGETYPE = "Image"
UBOOT_MACHINE = "qemu_arm64_defconfig"
IMAGE_BOOT_FILES = "${KERNEL_IMAGETYPE} boot.scr ${KERNEL_DTB_FILE}"
SPL_BINARY = "u-boot-sunxi-with-spl.bin"
SERIAL_CONSOLES ?= "115200;ttyAMA0 115200;hvc0"

# as for now neither graphics nor audio is supported
MACHINE_FEATURES:remove = "alsa x11"
MACHINE_FEATURES:append = "bluetooth wifi"
MACHINE_EXTRA_RRECOMMENDS = "uwe5622-firmware kernel-modules"

PREFERRED_PROVIDER_virtual/kernel = "linux-stable"


# For runqemu
QB_SYSTEM_NAME = "qemu-system-aarch64"

# Generic arm64 emulation
QB_MACHINE = "-machine virt"
QB_CPU = "-cpu cortex-a53"
QB_SMP ?= "-smp 4"
QB_CPU_KVM = "-cpu host -machine gic-version=3"

QB_ROOTFS_OPT = "\
    -drive if=none,file=@ROOTFS@,format=raw,id=mmc0 \
    -device virtio-blk-device,drive=mmc0 \
"

# Virtio serial console
QB_SERIAL_OPT = "\
    -device virtio-serial-pci -chardev null,id=virtcon \
    -device virtconsole,chardev=virtcon \
"

QB_TCPSERIAL_OPT = "\
    -device virtio-serial-pci -chardev socket,id=virtcon,port=@PORT@,host=127.0.0.1,nodelay=on \
    -device virtconsole,chardev=virtcon \
"
