require include/raspi3ap.inc

KERNEL_DEVICETREE = "broadcom/bcm2837-rpi-3-a-plus.dtb"
UBOOT_MACHINE = "rpi_3_32b_config"
SDIMG_KERNELIMAGE ?= "kernel7.img"
ENABLE_UART = "1"
SERIAL_CONSOLES ?= "115200;ttyS0"
ARMSTUB ?= "armstub7.bin"
RPI_USE_U_BOOT = "1"

MACHINE_EXTRA_RRECOMMENDS = "\
    kernel-modules \
    brcm-firmware \
    kernel-module-display7 \
"

IMAGE_BOOT_FILES = "\
    ${BOOTFILES_DIR_NAME}/* \
    bcm2837-rpi-3-a-plus.dtb \
    ${RPI_EXTRA_IMAGE_BOOT_FILES} \
"
